{
	TCanvas* c1=new TCanvas("c1","");
	c1->Divide(2,2);
	TCanvas* c2=new TCanvas("c2","");
	c2->Divide(2,2);
	
	Double_t norm;
	Double_t norm2;
	Int_t nBins;
	const Int_t bins=18;
	
	TFile *file1 = new TFile("histos_33mill_unpol_uncoll.root");
	TH1F* unpolarised_h=(TH1F*)file1->Get("dPhiAngle_Ewin");
	unpolarised_h->SetTitle("unpolarised simulation");
	norm=unpolarised_h->Integral(-180,180);
	nBins=unpolarised_h->GetNbinsX();
	norm=norm/nBins;
	norm2=unpolarised_h->GetBinContent(1);
	if(nBins%2==0){
		norm2+=unpolarised_h->GetBinContent(nBins/2);
		norm2+=unpolarised_h->GetBinContent(nBins/2+1);
	} else norm2+=unpolarised_h->GetBinContent(nBins/2+1);
	norm2+=unpolarised_h->GetBinContent(nBins);
	if(nBins%2==0) norm2=norm2/4;
	else norm2=norm2/3;
//	cout << norm << " " << nBins << endl;
	TH1F* unpolarisedNorm_h=(TH1F*)unpolarised_h->Clone("unpolarisedNorm_h");
	unpolarisedNorm_h->Scale(1/norm);
	TH1F* unpolarisedNorm2_h=(TH1F*)unpolarised_h->Clone("unpolarisedNorm2_h");
	unpolarisedNorm2_h->Scale(1/norm2);
	c1->cd(1);
	unpolarised_h->Draw();
	c2->cd(1);
	unpolarisedNorm_h->Draw();
	
	TFile *file2 = new TFile("histos_37mill_pol_uncoll.root");
	TH1F* polarised_h=(TH1F*)file2->Get("dPhiAngle_Ewin");
	polarised_h->SetTitle("polarised simulation");
	norm=polarised_h->Integral(-180,180);
	nBins=polarised_h->GetNbinsX();
	norm=norm/nBins;
	norm2=polarised_h->GetBinContent(1);
	if(nBins%2==0) {
		norm2+=polarised_h->GetBinContent(nBins/2);
		norm2+=polarised_h->GetBinContent(nBins/2+1);
	} else norm2+=polarised_h->GetBinContent(nBins/2+1);
	norm2+=polarised_h->GetBinContent(nBins);
	if(nBins%2==0) norm2=norm2/4;
	else norm2=norm2/3;
//	cout << norm << " " << nBins << endl;
	TH1F* polarisedNorm_h=(TH1F*)polarised_h->Clone("polarisedNorm_h");
	polarisedNorm_h->Scale(1/norm);
	TH1F* polarisedNorm2_h=(TH1F*)polarised_h->Clone("polarisedNorm2_h");
	polarisedNorm2_h->Scale(1/norm2);
	c1->cd(2);
	polarised_h->Draw();
	c2->cd(2);
	polarisedNorm_h->Draw();

	TFile *file3 = new TFile("histos_40mill_tangle_uncoll.root");
	TH1F* entangled_h=(TH1F*)file3->Get("dPhiAngle_Ewin");
	entangled_h->SetTitle("entangled simulation");
	norm=entangled_h->Integral(-180,180);
	nBins=entangled_h->GetNbinsX();
	norm=norm/nBins;
	norm2=entangled_h->GetBinContent(1);
	if(nBins%2==0) {
		norm2+=entangled_h->GetBinContent(nBins/2);
		norm2+=entangled_h->GetBinContent(nBins/2+1);
	} else norm2+=entangled_h->GetBinContent(nBins/2+1);
	norm2+=entangled_h->GetBinContent(nBins);
	if(nBins%2==0) norm2=norm2/4;
	else norm2=norm2/3;
//	cout << norm << " " << nBins << endl;
	TH1F* entangledNorm_h=(TH1F*)entangled_h->Clone("entangledNorm_h");
	entangledNorm_h->Scale(1/norm);
	TH1F* entangledNorm2_h=(TH1F*)entangled_h->Clone("entangledNorm2_h");
	entangledNorm2_h->Scale(1/norm2);
	c1->cd(3);
	entangled_h->Draw();
	c2->cd(3);
	entangledNorm_h->Draw();
	
	TFile *file4 = new TFile("newData.root");
	TH1F* expt_h=(TH1F*)file4->Get("dPhiAngle_Ewin");
	expt_h->SetTitle("experimental data");
	expt_h->SetYTitle("Normalised Coincidence Count Rate");
//	expt_h->SetYTitle("Normalised Scattering Probability");
	norm=expt_h->Integral(-180,180);
	nBins=expt_h->GetNbinsX();
	norm=norm/nBins;
	norm2=expt_h->GetBinContent(1);
	if(nBins%2==0) {
		norm2+=expt_h->GetBinContent(nBins/2);
		norm2+=expt_h->GetBinContent(nBins/2+1);
	} else norm2+=expt_h->GetBinContent(nBins/2+1);
	norm2+=expt_h->GetBinContent(nBins);
	if(nBins%2==0) norm2=norm2/4;
	else norm2=norm2/3;
//	cout << norm << " " << nBins << endl;
	TH1F* exptNorm_h=(TH1F*)expt_h->Clone("exptNorm_h");
	exptNorm_h->Scale(1/norm);
	TH1F* exptNorm2_h=(TH1F*)expt_h->Clone("exptNorm2_h");
	exptNorm2_h->Scale(1/norm2);
	c1->cd(4);
	expt_h->Draw();
	c2->cd(4);
	exptNorm_h->Draw();
	
	TCanvas* c3=new TCanvas("c3","Normalised to mean (no errors on sims)");
	c3->cd();
	exptNorm_h->SetLineColor(1);
	exptNorm_h->SetMarkerColor(1);
	exptNorm_h->SetMarkerStyle(21);
	exptNorm_h->SetBit( TH1::kNoTitle, true );
	exptNorm_h->GetXaxis()->SetTitle("#Delta#phi (degrees)");
	exptNorm_h->GetXaxis()->SetLabelSize(0.05);
	exptNorm_h->GetXaxis()->SetTitleSize(0.05);
	exptNorm_h->GetXaxis()->SetTitleOffset(0.9);
	exptNorm_h->GetYaxis()->SetLabelSize(0.05);
	exptNorm_h->GetYaxis()->SetTitleSize(0.05);
	exptNorm_h->GetYaxis()->SetTitleOffset(0.9);
//	exptNorm_h->SetLineColor(1);
	exptNorm_h->SetMarkerStyle(21);
	exptNorm_h->SetBit( TH1::kNoTitle, true );
	exptNorm_h->GetXaxis()->SetTitle("#Delta#phi (degrees)");
	exptNorm_h->DrawCopy("e1");
//	entangledNorm_h->SetLineColor(2);
//	entangledNorm_h->Draw("e3 pfc same");
	entangledNorm_h->SetLineColor(4);
	entangledNorm_h->DrawCopy("hist l same");
//	polarisedNorm_h->SetLineColor(3);
//	polarisedNorm_h->Draw("e3 pfc same");
	polarisedNorm_h->SetLineColor(2);
	polarisedNorm_h->DrawCopy("hist l same");
//	unpolarisedNorm_h->SetLineColor(4);
//	unpolarisedNorm_h->Draw("e3 pfc same");
	unpolarisedNorm_h->SetLineColor(3);
	unpolarisedNorm_h->DrawCopy("hist l same");
	auto legend=new TLegend(0.4,0.78,0.95,0.95);
	legend->SetNColumns(2);
	legend->AddEntry(exptNorm2_h,"expt. data","lep");
	legend->AddEntry(entangledNorm2_h,"entangled sim.","l");
	legend->AddEntry(polarisedNorm2_h,"polarised sim.","l");
	legend->AddEntry(unpolarisedNorm2_h,"unpolarised sim.","l");
	legend->Draw();

//	c3->BuildLegend(0.6,0.8,0.95,0.95);
	
	TCanvas* c5=new TCanvas("c5","Norm2alised to dPhi=0, no errors on sims");
	c5->cd();
	exptNorm2_h->SetLineColor(1);
	exptNorm2_h->SetMarkerColor(1);
	exptNorm2_h->SetMarkerStyle(21);
	exptNorm2_h->SetBit( TH1::kNoTitle, true );
	exptNorm2_h->GetXaxis()->SetTitle("#Delta#phi (degrees)");
	exptNorm2_h->GetXaxis()->SetLabelSize(0.05);
	exptNorm2_h->GetXaxis()->SetTitleSize(0.05);
	exptNorm2_h->GetXaxis()->SetTitleOffset(0.9);
	exptNorm2_h->GetYaxis()->SetLabelSize(0.05);
	exptNorm2_h->GetYaxis()->SetTitleSize(0.05);
	exptNorm2_h->GetYaxis()->SetTitleOffset(0.9);
	exptNorm2_h->DrawCopy("e1");
	entangledNorm2_h->SetLineColor(4);
	entangledNorm2_h->DrawCopy("hist l same");
	polarisedNorm2_h->SetLineColor(2);
	polarisedNorm2_h->DrawCopy("hist l same");
	unpolarisedNorm2_h->SetLineColor(3);
	unpolarisedNorm2_h->DrawCopy("hist l same");
	auto legend2=new TLegend(0.4,0.78,0.95,0.95);
	legend2->SetNColumns(2);
	legend2->AddEntry(exptNorm2_h,"expt. data","lep");
	legend2->AddEntry(entangledNorm2_h,"entangled sim.","l");
	legend2->AddEntry(polarisedNorm2_h,"polarised sim.","l");
	legend2->AddEntry(unpolarisedNorm2_h,"unpolarised sim.","l");
	legend2->Draw();
//	c5->BuildLegend(0.5,0.78,0.95,0.98);
//	c5->BuildLegend(0.6,0.8,0.95,0.95);

	TCanvas* chi2_1_c=new TCanvas("chi2_1_c","Chi^2 normalised to integral");
	TCanvas* chi2_2_c=new TCanvas("chi2_2_c","Chi^2 normalised to dPhi=0");
	TH1F* chi2_1_h=new TH1F("chi2_1_h","(Expt Data - Entagled Sim)^2/errors^2",bins,-180,180);
	TH1F* chi2_2_h=new TH1F("chi2_2_h","(Expt Data - Polarised Sim)^2/errors^2",bins,-180,180);
	TH1F* chi2_3_h=new TH1F("chi2_3_h","(Expt Data - Entagled Sim)^2/errors^2",bins,-180,180);
	TH1F* chi2_4_h=new TH1F("chi2_4_h","(Expt Data - Polarised Sim)^2/errors^2",bins,-180,180);
	chi2_1_h->SetStats(0);
	chi2_2_h->SetStats(0);
	chi2_3_h->SetStats(0);
	chi2_4_h->SetStats(0);
	Float_t residual1,residual2,residual3,residual4;
	Float_t res1[bins],res2[bins],res3[bins],res4[bins];
	Float_t dPhi[bins];
	Float_t err3[bins], err4[bins];
	Float_t eDPhi[bins];
	Float_t error1,error2,error3,error4,error5,error6;
//	cout << "Index	Expt - Entangled	Expt - Polarised	Error" << endl;
	for(int i=1;i<=nBins;i++) {
		residual1=(exptNorm_h->GetBinContent(i) - entangledNorm_h->GetBinContent(i));
		res1[i-1]=residual1;
		residual2=(exptNorm_h->GetBinContent(i) - polarisedNorm_h->GetBinContent(i));
		res2[i-1]=residual2;
		error1=exptNorm_h->GetBinError(i);
		error2=entangledNorm_h->GetBinError(i);
		error3=polarisedNorm_h->GetBinError(i);
		
		residual3=(exptNorm2_h->GetBinContent(i) - entangledNorm2_h->GetBinContent(i));
		res3[i-1]=residual3;
		residual4=(exptNorm2_h->GetBinContent(i) - polarisedNorm2_h->GetBinContent(i));
		res4[i-1]=residual4;
		error4=exptNorm2_h->GetBinError(i);
		error5=entangledNorm2_h->GetBinError(i);
		error6=polarisedNorm2_h->GetBinError(i);
		
		err3[i-1]=sqrt(pow(error4,2)+pow(error5,2));
		err4[i-1]=sqrt(pow(error4,2)+pow(error6,2));
		
//		cout << i << "	" << residual1 << "		" << residual2 << "		" << error1 << "	" << residual3 << "	" << residual4 << "	" << error2 << endl;

		residual1=(residual1*residual1)/(error1*error1+error2*error2);
		chi2_1_h->SetBinContent(i,residual1);
		residual2=(residual2*residual2)/(error1*error1+error3*error3);
		chi2_2_h->SetBinContent(i,residual2);
		residual3=(residual3*residual3)/(error4*error4+error5*error5);
		chi2_3_h->SetBinContent(i,residual3);
		residual4=(residual4*residual4)/(error4*error4+error6*error6);
		chi2_4_h->SetBinContent(i,residual4);
		
		dPhi[i-1]=20*(i-1)-170;
		eDPhi[i-1]=0;
//		eDPhi[i-1]=180./bins;
	}
	chi2_1_c->cd();
	chi2_2_h->SetLineColor(2);
	chi2_2_h->GetXaxis()->SetTitle("#Delta#phi (degrees)");
	chi2_2_h->Draw("");
	chi2_1_h->GetXaxis()->SetTitle("#Delta#phi (degrees)");
	chi2_1_h->Draw("same");
	Float_t chi2_1=chi2_1_h->Integral();
	Float_t chi2_2=chi2_2_h->Integral();
	chi2_1_c->BuildLegend(0.4,0.75,0.9,0.9);
	
	chi2_2_c->cd();
	chi2_4_h->SetLineColor(2);
	chi2_4_h->GetXaxis()->SetTitle("#Delta#phi (degrees)");
	chi2_4_h->Draw("");
	chi2_3_h->GetXaxis()->SetTitle("#Delta#phi (degrees)");
	chi2_3_h->Draw("same");
	Float_t chi2_3=chi2_3_h->Integral();
	Float_t chi2_4=chi2_4_h->Integral();
	chi2_2_c->BuildLegend(0.4,0.75,0.9,0.9);

	Int_t ndf1=chi2_1_h->GetNbinsX()-1;
	Int_t ndf2=chi2_2_h->GetNbinsX()-1;
	Int_t ndf3=chi2_3_h->GetNbinsX()-1;
	Int_t ndf4=chi2_4_h->GetNbinsX()-1;

	cout << endl << "Normailised to integral" << endl;
	cout << "			Chi^2 / ndf" << endl;
	cout << "Expt-Entangled Sim:	" << chi2_1 << " / " << ndf1 << " = " << chi2_1/ndf1 << endl;
	cout << "Expt-Polarised Sim:	" << chi2_2 << " / " << ndf2 << " = " << chi2_2/ndf2 << endl;
	
	cout << endl << "Normailised to dPhi=0" << endl;
	cout << "			Chi^2 / ndf" << endl;
	cout << "Expt-Entangled Sim:	" << chi2_3 << " / " << ndf3 << " = " << chi2_3/ndf3 << endl;
	cout << "Expt-Polarised Sim:	" << chi2_4 << " / " << ndf4 << " = " << chi2_4/ndf4 << endl;
	
	TCanvas* c4=new TCanvas("c4","Norm2alised to dPhi=0");
	c4->cd();
	exptNorm2_h->SetLineColor(1);
	exptNorm2_h->SetMarkerColor(1);
	exptNorm2_h->SetMarkerStyle(21);
	exptNorm2_h->SetBit( TH1::kNoTitle, true );
	exptNorm2_h->GetXaxis()->SetTitle("#Delta#phi (degrees)");
	exptNorm2_h->DrawCopy("e1");
	entangledNorm2_h->SetLineColor(4);
	entangledNorm2_h->SetFillColor(4);
//	entangledNorm2_h->Draw("e3");
	entangledNorm2_h->Draw("e3 same");
	polarisedNorm2_h->SetLineColor(2);
	polarisedNorm2_h->SetFillColor(2);
	polarisedNorm2_h->Draw("e3 same");
	unpolarisedNorm2_h->SetLineColor(3);
	unpolarisedNorm2_h->SetFillColor(3);
	unpolarisedNorm2_h->Draw("e3 same");
	exptNorm2_h->DrawCopy("e1 same");
	auto legend3=new TLegend(0.4,0.88,0.95,0.98);
	legend3->SetNColumns(2);
	TLegendEntry* l1=legend3->AddEntry(exptNorm_h,"expt. data","lep");
	TLegendEntry* l2=legend3->AddEntry(entangledNorm_h,"QE-Geant4","l");
	l2->SetTextColor(4);
	TLegendEntry* l3=legend3->AddEntry(polarisedNorm_h,"Geant4 (pol.)","l");
	l3->SetTextColor(2);
	TLegendEntry* l4=legend3->AddEntry(unpolarisedNorm_h,"Geant4 (unpol.)","l");
	l4->SetTextColor(3);
	legend3->Draw();
//	c4->BuildLegend(0.6,0.8,0.95,0.95);
	
	TCanvas* c6=new TCanvas("c6","Normalised to mean ");
	c6->cd();
	exptNorm_h->DrawCopy("e1");
	entangledNorm_h->SetLineColor(4);
	entangledNorm_h->SetFillColor(4);
	entangledNorm_h->DrawCopy("e3 same");
	polarisedNorm_h->SetLineColor(2);
	polarisedNorm_h->SetFillColor(2);
	polarisedNorm_h->DrawCopy("e3 same");
	unpolarisedNorm_h->SetLineColor(3);
	unpolarisedNorm_h->SetFillColor(3);
	unpolarisedNorm_h->DrawCopy("e3 same");
	exptNorm_h->Draw("e1 same");
	auto legend4=new TLegend(0.4,0.88,0.95,0.98);
//	auto legend4=new TLegend(0.4,0.78,0.95,0.95);
	legend4->SetNColumns(2);
	legend4->AddEntry(exptNorm_h,"expt. data","lep");
	legend4->AddEntry(entangledNorm_h,"QE-Geant4","l");
	legend4->AddEntry(polarisedNorm_h,"Geant4 (pol.)","l");
	legend4->AddEntry(unpolarisedNorm_h,"Geant4 (unpol.)","l");
	legend4->Draw();
//	c6->BuildLegend(0.6,0.75,0.9,0.9);
//
//	TCanvas* c6=new TCanvas("c6","Norm2alised to dPhi=0");
//	c6->cd();
////	exptNorm2_h->SetFillColor(1);
//	exptNorm2_h->Draw("e1");
//	entangledNorm2_h->Draw("e1 same");
//	polarisedNorm2_h->Draw("e1 same");
//	unpolarisedNorm2_h->Draw("e1 same");
//	c6->BuildLegend(0.6,0.75,0.9,0.9);

	TCanvas* residuals_c = new TCanvas("resuduals_c","Residuals");
	TGraphErrors* res3_g=new TGraphErrors(bins,dPhi,res3,eDPhi,err3);
	TGraphErrors* res4_g=new TGraphErrors(bins,dPhi,res4,eDPhi,err3);
	
	res4_g->SetTitle(";#Delta#phi (degrees);Residual");
	res4_g->SetMarkerStyle(22);
	res4_g->SetMarkerColor(2);
	res4_g->SetLineColor(2);
//	res4_g->GetHistogram()->SetMinimum(-1*res4_g->GetHistogram()->GetMaximum());
//	res4_g->GetHistogram()->SetMinimum(1.1*res3_g->GetHistogram()->GetMinimum());
	res4_g->GetHistogram()->SetMinimum(-0.3);
	res4_g->GetHistogram()->SetMaximum(0.6);
	res4_g->GetHistogram()->GetXaxis()->SetLabelSize(0.05);
	res4_g->GetHistogram()->GetXaxis()->SetTitleSize(0.05);
	res4_g->GetHistogram()->GetXaxis()->SetTitleOffset(0.9);
	res4_g->GetHistogram()->GetYaxis()->SetLabelSize(0.05);
	res4_g->GetHistogram()->GetYaxis()->SetTitleSize(0.05);
	res4_g->GetHistogram()->GetYaxis()->SetTitleOffset(0.9);
	res4_g->GetXaxis()->SetLimits(-180,180);
	res4_g->Draw("ALP");
	res3_g->SetMarkerStyle(20);
	res3_g->SetMarkerColor(4);
	res3_g->SetLineColor(4);
	res3_g->Draw("LP same");
	
	auto res_leg=new TLegend(0.55,0.88,0.95,0.98);
	TLegendEntry* resLeg1=res_leg->AddEntry(res3_g,"expt. data - QE-Geant4","lep");
	TLegendEntry* resLeg2=res_leg->AddEntry(res4_g,"expt. data - Geant4","lep");
	res_leg->Draw("");
	TLine* line=new TLine(-180,0,180,0);
	line->Draw("same");

}
